console.log("Olá mundo Git!");
console.log("Arquivo Alterado!");
console.log("Mudança de branch");
console.log("Mudança de branch 2");
alert("Testando...");
console.log("Olá mundo Git!");
console.log("Arquivo Alterado!");
alert("Acrescimo de codigo");
console.log("teste de conflito");
console.log("comando merge");
